"""Initial migration

Revision ID: 345ea966dca0
Revises:
Create Date: 2026-04-16 22:51:13.734146

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "345ea966dca0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxy_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("secret", sa.String(length=32), nullable=False),
        sa.Column("tg_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proxy_keys_id"), "proxy_keys", ["id"], unique=False)
    op.create_index(op.f("ix_proxy_keys_tg_user_id"), "proxy_keys", ["tg_user_id"], unique=False)
    op.create_index(op.f("ix_proxy_keys_username"), "proxy_keys", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proxy_keys_username"), table_name="proxy_keys")
    op.drop_index(op.f("ix_proxy_keys_tg_user_id"), table_name="proxy_keys")
    op.drop_index(op.f("ix_proxy_keys_id"), table_name="proxy_keys")
    op.drop_table("proxy_keys")
    # ### end Alembic commands ###
